### Change driver availability – set available
PUT http://localhost:8080/api/drivers/1/availability
Content-Type: application/json

{
  "available": true
}

### Change driver availability – set unavailable
PUT http://localhost:8080/api/drivers/1/availability
Content-Type: application/json

{
  "available": false
}


### Request driver logout
POST http://localhost:8080/api/drivers/1/logout-requests

