### Register a new passenger account
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test.passenger@example.com",
  "password": "Password123",
  "firstName": "John",
  "lastName": "Doe",
  "address": "123 Main St, Cityville",
  "phoneNumber": "+381601234567",
  "profilePicture": "https://example.com/profile.png"
}


### Activate the newly registered account
POST http://localhost:8080/api/auth/activations
Content-Type: application/json

{
  "token": "test.passenger@example.com"
}