export enum NotificationType {
  RIDE_ACCEPTED = 'RIDE_ACCEPTED',
  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RIDE_CREATED = 'RIDE_CREATED',
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PANIC_ACTIVATED = 'PANIC_ACTIVATED',
  RIDE_SCHEDULED = 'RIDE_SCHEDULED',
  RIDE_REMINDER = 'RIDE_REMINDER',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION'
}
